disabled = false
languageCode = "pt-pt"
languageName = "Português"
weight = 10
title = "Lampreia Viva"

[params]
  displayName = "Português"
  isoCode = "pt-pt"
  rtl = false
  dateFormat = "2 January 2006"
