disabled = true
languageCode = "en"
languageName = "English"
weight = 1
title = "Lampreia Viva"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  landingPageTitle = "Lampreia Viva"
  landingPageSubTitle = "Recording and production studio based in Porto, Portugal"